version: '3.8'


services:
  bot:
    build: ../../Downloads
    container_name: Kurmanbek
    volumes:
      - .:/app
      - db_data:/app/db
    command: python main.py
    network_mode: 'host'


volumes:
  db_data:
